platform :ios, '9.0'

use_frameworks!

target 'ZYCoverController_Example' do
  pod 'ZYCoverController', :path => '../'

  target 'ZYCoverController_Tests' do
    inherit! :search_paths

    
  end
end
